LOG_ACTIVE = False
SANDBOX_ACTIVE = False
PLAYER_TURN = True
PLAYER_ACTIVE = True
INITIAL_POSITION = (3, 2, 5)
NUMBER_OF_STICKS = 16
ANBOT_MODE = 'SCORING' # SCORING | THINKING | HYBRID
DIGGING_LEVEL = 4